services:
  frontend:
    image: dakshsawhneyy/incidentzero-frontend:v1
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - incidentzero
  backend:
    image: dakshsawhneyy/incidentzero-backend:v1
    container_name: backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 4000
      DB_SSL: true
      CORS_ORIGIN: http://localhost:5173
    networks:
      - incidentzero

networks:
  incidentzero: